---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidync)
library(osmdata)
library(ggthemes)
library(sf)
library(epitools)
```

```{r}
available_data <- function(web_link = "https://cida.usgs.gov/thredds/dodsC/macav2metdata_daily_future",
                           verbose = TRUE){
  
  message('Trying to connect to the USGS.gov API')
  
  src <- tidync(web_link)

  message('Reading results')
  
variable_names <- src$variable %>% dplyr::select(name) 
variable_names <- variable_names[-1:-4,]

available_times <- src %>% activate("D3") %>% hyper_tibble()

colnames(variable_names) <- "Available variable"
colnames(available_times) <- "Available times"
available_times$`Available times` <- as.numeric(available_times$`Available times`)
if(verbose==FALSE){
return(list(
"variable_names" = variable_names, 
"available_times" = available_times,
"src" = src
))  
}else{
  message('Converting into an R data.table')
  
mydates <- seq.Date(as.Date("2006-01-01"), 
                                 as.Date("2099-12-31"), 
                                 by = 1)

myjulian <- julian(mydates, origin=as.Date("1900-01-01"))
time_library <- as.data.frame(cbind("Available times" = myjulian, dates = as.character(julian2date(myjulian))))
time_library$`Available times` <- as.numeric(time_library$`Available times`)

available_times <- as.data.frame(available_times) %>% left_join(time_library, by = "Available times")

available_times$`Available times` <- as.numeric(available_times$`Available times`)


      scenarios <- as.data.frame(matrix(c("rcp45", "rcp85", "RCP 4.5", "RCP 8.5"), 2,2, byrow=FALSE))
      colnames(scenarios) <- c("scenario_abbreviation","scenario_name")
      
     
      
      labels <- as.data.frame(matrix(c("tasmin" , "Minimum Temperature",
                    "tasmax" , "Maximum Temperature",
                    "rhsmin" , "Minimum Relative Humidity",
                    "rhsmax" , "Maximum Relative Humidity",
                    "pr" , "Precipitation",
                    "rsds" , "Surface Downswelling Shortwave Flux",
                    "uas" , "Eastward Wind",
                    "vas" , "Northward Wind",
                    "huss" , "Specific Humidity",
                    "vpd" , "Vapor Pressure Deficit",
                    "rcp45" , "Representative Concentration Pathway 4.5",
                    "rcp85" , "Representative Concentration Pathway 8.5",
                    "bcc-csm1-1" , "Beijing Climate Center - Climate System Model 1.1",
                    "bcc-csm1-1m" , "Beijing Climate Center - Climate System Model 1.1 Moderate Resolution",
                    "BNU-ESM" , "Beijing Normal University - Earth System Model",
                    "CanESM2" , "Canadian Earth System Model 2",
                    "CCSM4" , "Community Climate System Model 4",
                    "CNRM-CM5" , "Centre National de Recherches M\U00E9t\U00E9orologiques - Climate Model 5",
                    "CSIRO-Mk3-6-0" , "Commonwealth Scientific and Industrial Research Organisation - Mk3.6.0",
                    "GFDL-ESM2M" , "Geophysical Fluid Dynamics Laboratory - Earth System Model 2 Modular Ocean",  
                    "GFDL-ESM2G" , "Geophysical Fluid Dynamics Laboratory - Earth System Model 2 Generalized Ocean Layer Dynamics",
                    "HadGEM2-ES365" , "Hadley Global Environment Model 2 - Earth System 365 (day)",
                    "HadGEM2-CC365" , "Hadley Global Environment Model 2 - Climate Chemistry 365 (day) ", 
                    "inmcm4" , "Institute of Numerical Mathematics Climate Model 4",
                    "IPSL-CM5A-LR" , "Institut Pierre Simon Laplace (IPSL) - Climate Model 5A - Low Resolution",
                    "IPSL-CM5A-MR" , "Institut Pierre Simon Laplace (IPSL) - Climate Model 5A - Medium Resolution",
                    "IPSL-CM5B-LR" , "Institut Pierre Simon Laplace (IPSL) - Climate Model 5B - Low Resolution",
                    "MIROC5" , "Model for Interdisciplinary Research On Climate 5",      
                    "MIROC-ESM" , "Model for Interdisciplinary Research On Climate - Earth System Model",
                    "MIROC-ESM-CHEM" , "Model for Interdisciplinary Research On Climate - Earth System Model - Chemistry",
                    "MRI-CGCM3" , "Meteorological Research Institute - Coupled Global Climate Model 3",
                    "NorESM1-M" , "Norwegian Earth System Model 1 - Medium Resolution"), 32, 2, byrow=TRUE))
      
      labels <- as.data.frame(cbind(labels[,1], labels[,1], labels[,2]))
      colnames(labels) <- c("variable_abbreviation","model_abbreviation","name")
      
      units <- as.data.frame(matrix(c("Minimum Temperature" , "K",
                                      "Maximum Temperature" , "K",
                   "Minimum Relative Humidity" , "%",
                   "Maximum Relative Humidity" , "%",
                   "Precipitation" , "mm",
                   "Surface Downswelling Shortwave Flux" , "W m-2",
                   "Eastward Wind" , "m s-1",
                   "Northward Wind" , "m s-1",
                   "Specific Humidity" , "kg kg-1",
                   "Vapor Pressure Deficit" , "kPa"), 10,2, byrow=TRUE))
      colnames(units) <- c("Variable","Units")
      
      
      
variable_names_verbose  <- variable_names %>% separate("Available variable", "_",
                into = c("variable_abbreviation", "model_abbreviation", "ensemble","scenario_abbreviation"), 
                remove = FALSE)

variable_names_verbose <- variable_names_verbose  %>% 
  left_join(labels %>% select("variable_abbreviation","name"), by=c("variable_abbreviation")) %>% 
  left_join(labels %>% select("model_abbreviation","name"), by=c("model_abbreviation")) %>% 
  left_join(scenarios, by=c("scenario_abbreviation")) 





names(variable_names_verbose) <- c("Available variable", "Variable abbreviation",
                                                            "Model abbreviation",
                                                            "Model ensemble type (only CCSM4 relevant)",
                                                            "Scenario abbreviation",
                                                            "Variable",
                                                            "Model",
                                                            "Scenario")

variable_names_verbose <- variable_names_verbose  %>% 
  left_join(units, by=c("Variable"))


variable_names_verbose <- variable_names_verbose %>% select("Available variable",
                                                            "Variable",
                                                            "Units",
                                                            "Model",
                                                            "Model ensemble type (only CCSM4 relevant)",
                                                            "Scenario",
                                                            "Variable abbreviation",
                                                            "Model abbreviation",
                                                            "Scenario abbreviation"
                                                            )



variable_names <- variable_names_verbose

return(list(
"variable_names" = variable_names, 
"available_times" = available_times,
"src" = src
))   
}}

inputs <- available_data()
inputs
```


```{r}
# Year 2034
time_min <- 72048
time_max <- 73048

input_times <- inputs$available_times %>% add_column(index = 0) 
input_times[which(inputs$available_times[,1] > time_min & inputs$available_times[,1] < time_max ),3] <- 1

tail(input_times)

```

```{r}
input_variables <- inputs$variable_names %>% 
  filter(Variable == "Specific Humidity") %>% 
  filter(Model == c("Beijing Normal University - Earth System Model", "Hadley Global Environment Model 2 - Earth System 365 (day)")) %>%
  filter(Scenario == c("RCP 4.5", "RCP 8.5")) %>% 
  pull("Available variable")

input_variables
```



```{r}
bb <- getbb("yellowstone")
bb_manual <- bb
bb_manual[1,1] <- -111.15594815937659
bb_manual[1,2] <- -109.8305463801207
bb_manual[2,1] <- 44.12354048271325
bb_manual[2,2] <- 45.11911641599412

my_boundary <- opq(bb_manual) %>% 
  add_osm_feature(key = "boundary", value = "national_park") %>% 
osmdata_sf() 

my_boundary
```

```{r}
boundaries <- my_boundary$osm_multipolygons
pulled_bb <- st_bbox(boundaries)
pulled_bb
```


```{r, cache=TRUE, warning=FALSE}
basemap <- ggplot(data = boundaries) +
  geom_sf(fill = "cornflowerblue") +
  geom_sf_text(aes(label = boundaries$name)) 

basemap
```


```{r, cache=TRUE}

Pulled_data <- inputs$src %>% 
  hyper_filter(lat = lat <= c(pulled_bb[4]+0.05) & lat >= c(pulled_bb[2]-0.05)) %>% 
  hyper_filter(lon = lon <= c(pulled_bb[3]+0.05) & lon >= c(pulled_bb[1]-0.05)) %>% 
  hyper_filter(time =  input_times[,3] == 1) %>% 
  hyper_tibble(select_var = input_variables
    ) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326, agr = "constant")

print(Pulled_data)
```




```{r}
check_filter <- Pulled_data %>% filter(time == min(Pulled_data$time))

ggplot() +
  geom_sf(data = boundaries, fill = "cornflowerblue") +
 geom_sf(data = check_filter, color = "red", size=0.1) +
  coord_sf(crs = 4326) 
```



```{r}
library(stars)
rast <- st_rasterize(Pulled_data)
plot(rast)

```

```{r}
extracted <- st_extract(rast, boundaries$geometry) %>% st_as_sf()

ggplot(data=extracted) +
  geom_sf(aes(fill = huss_BNU.ESM_r1i1p1_rcp45)) +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white")+
  coord_sf(crs = 4326)
```


```{r, eval=FALSE}
cube <- src_slc %>% hyper_tbl_cube(select_var = c("huss_BNU-ESM_r1i1p1_rcp45"))
cube
```


```{r}

intersection <- st_intersection(x = Pulled_data, y = boundaries)

int_result <- intersection %>% 
  group_by(osm_id) 

```


```{r}
ggplot() +
  geom_sf(data = int_result, aes(color=huss_BNU.ESM_r1i1p1_rcp45)) +
  scale_color_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white")+
  geom_sf(data = boundaries, fill = NA, color = "white") +
  theme_tufte()+
  labs(title = "YELLOWSTONE NATIONAL PARK", subtitle = "Temperture in 2050")
```


```{r, fig.width=5}
ggplot() +
  geom_sf(data = int_result, aes(color=huss_BNU.ESM_r1i1p1_rcp45)) +
  geom_sf(data = boundaries, fill = NA, color = NA) +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white")+
  facet_grid(cols = vars(name)) +
  theme_tufte() 
```



```{r, fig.height=10}
river <- opq(bb_manual) %>%
  add_osm_feature(key = "waterway", value = "river") %>%
  osmdata_sf() 
river
```

```{r}
river_sub <- st_buffer(river$osm_lines, 2200)
extracted_river <- st_extract(rast,  river_sub$geometry ) %>% st_as_sf()
extracted_river
#colnames(extracted_river)[1] <- "var1"

```

```{r, fig.height=3}
ggplot(data=extracted_river) +
  geom_sf(aes(fill = huss_BNU.ESM_r1i1p1_rcp45), size=0) +
   coord_sf(crs = 4326, xlim = c(pulled_bb[1], pulled_bb[3]), 
           ylim = c(pulled_bb[2], pulled_bb[4]),
           expand = FALSE) +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white")+
  labs(title = "Rivers of Yellowstone",
       subtitle = "Projected humidity in 2040", 
       caption = "Data Source: Climate Futures...") + 
  theme_tufte()
```


```{r, fig.height=10}
roads <- opq(bb_manual) %>%
  add_osm_feature(key = 'highway', value = 'primary') %>%
  add_osm_feature(key = 'highway', value = 'secondary') %>%
  osmdata_sf() 
roads_sub <- st_buffer(roads$osm_lines, 2200)
extracted_roads <- st_extract(rast,  roads_sub$geometry ) %>% st_as_sf()
extracted_roads
```
```{r, fig.height=3}
ggplot(data=extracted_roads) +
  geom_sf(aes(fill = huss_BNU.ESM_r1i1p1_rcp45), size=0) +
   coord_sf(crs = 4326) +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white")+
  labs(title = "Roads of Yellowstone",
       subtitle = "Projected humidity in 2040", 
       caption = "Data Source: Climate Futures...") + 
  theme_tufte()
```

