#' Generate a climate data frame of spatial averages from the file
#' reference object generated by cftdata. Averages represent all
#' grid cells within or touching the area of interest provided to cftdata.
#'
#' @param file_reference A file reference data frame generated by `cftdata()`
#' @param ncores Number of cores to use (int)
#' 
#' @return A tibble of climate data averaged spatially over an area of interest.
#' 
#' @examples 
#' \dontrun{
#' file_ref <- cftdata(park = "Acadia National Park", 
#'                     parameters = "pr", 
#'                     years = c(2020, 2021), 
#'                     models = "CCSM4", 
#'                     scenarios = "rcp85")
#' df <- cft_df(file_ref, ncores = parallel::detectCores())
#' }
#' 
#' @importFrom magrittr %>%
#' 
#' @export
cft_df <- function(file_reference, ncores = 1) {
  
  # Create long form data frame
  message("Computing spatial averages...")
  cl <- parallel::makeCluster(ncores)
  on.exit(parallel::stopCluster(cl))
  df <- pbapply::pbapply(file_reference,
                         MARGIN = 1,
                         FUN = r_to_df,
                         cl = cl) %>%
    dplyr::bind_rows()

  # Conver to wide form
  message("Generating climate data.frame...")
  wide_df <- split(df, df$date) %>%
    pbapply::pblapply(FUN = tidyr::pivot_wider, 
                      names_from = "parameter",
                      values_from = "value", 
                      cl = cl) %>%
    dplyr::bind_rows()
  wide_df
}

# internal function that computes spatial average of raster
r_to_df <- function(df_row) {
  path <- df_row[["local_path"]]
  varname <- df_row[["parameter_long"]]
  r <- raster::brick(x=path, varname=varname)

  min_date <- as.Date(paste0(df_row["year1"], "-01-01"))
  max_date <- as.Date(paste0(df_row["year2"], "-12-31"))
  date_seq <- seq(min_date, max_date, 1)
  tibble::tibble(
    value = raster::cellStats(r, stat = "mean"), 
    parameter = df_row["parameter"], 
    rcp = df_row["rcp"], 
    date = date_seq, 
    model = df_row["model"],
    ensemble = df_row["ensemble"], 
    area_name = df_row["area_name"]
  )
}

