#' Generate a climate data frame
#'
#' @param file_reference A file reference data frame generated by `cstdata()`
#' @param ncores Number of cores to use (int)
#' 
#' @return A tibble of climate data averaged spatially over an area of interest.
#' 
#' @examples 
#' \dontrun{
#' file_ref <- cstdata(park = "Acadia National Park", 
#'                     parameters = "pr", 
#'                     years = c(2020, 2021), 
#'                     models = "CCSM4", 
#'                     scenarios = "rcp85")
#' df <- cst_df(file_ref, cores = parallel::detectCores())
#' }
#' 
#' @importFrom magrittr %>%
#' 
#' @export
cst_df <- function(file_reference, ncores = 1) {
  
  # Create long form data frame
  message("Computing spatial averages...")
  cl <- parallel::makeCluster(ncores)
  on.exit(parallel::stopCluster(cl))
  df <- pbapply::pbapply(file_reference,
                         MARGIN = 1,
                         FUN = r_to_df,
                         cl = cl) %>%
    dplyr::bind_rows()

  # Convert Kelvin to Celsius
  df = to_celsius(df)

  # Conver to wide form
  message("Generating climate data.frame...")
  wide_df <- split(df, df$date) %>%
    pbapply::pblapply(FUN = tidyr::pivot_wider, 
                      names_from = "parameter",
                      values_from = "value", 
                      cl = cl) %>%
    dplyr::bind_rows()
  wide_df
}

# internal function that computes spatial average of raster
r_to_df <- function(df_row) {
  path <- df_row[["local_path"]]
  varname <- df_row[["parameter_long"]]
  r <- raster::brick(x=path, varname=varname)

  min_date <- as.Date(paste0(df_row["year1"], "-01-01"))
  max_date <- as.Date(paste0(df_row["year2"], "-12-31"))
  date_seq <- seq(min_date, max_date, 1)
  tibble::tibble(
    value = raster::cellStats(r, stat = "mean"), 
    parameter = df_row["parameter"], 
    rcp = df_row["rcp"], 
    date = date_seq, 
    model = df_row["model"],
    ensemble = df_row["ensemble"], 
    area_name = df_row["area_name"]
  )
}

# convert file reference object temperature from kelvin to celsius if necessary
to_celsius <- function(df) {

  # Check for temperature variables ("tasmin" or "tasmax")
  temperature_rows <- grep("tas", df$parameter)

  # Alert user to conversion if temperature is found
  if (length(temperature_rows) > 0) message("Converting Kelvin to Celsius...")

  # And convert
  temperature_kelvin <- unlist(df[["value"]][temperature_rows])
  temperature_c <- temperature_kelvin - 273.15
  df[["value"]][temperature_rows] <- temperature_c

  return(df)
}
